name: chatgpt_flutter_app
description: "A simple GPT-4o-powered Flutter chat app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ✅ Include assets like .env (though not required unless read as asset)
  assets:
    - .env

  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
